service: so-v6

plugins:
  - serverless-offline

custom:
  # serverless-offline v6
  serverless-offline:
    showDuration: true
    httpPort: 3006
    lambdaPort: 3007

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

functions:
  invokeEvent:
    handler: lambdaInvokeHandler.invokeEvent
    events:
      - http:
          method: get
          path: invoke-event

  invokeRequestResponse:
    handler: lambdaInvokeHandler.invokeRequestResponse
    events:
      - http:
          method: get
          path: invoke-request-response

  invokedHandler:
    handler: lambdaInvokeHandler.invokedHandler

  invokeAsync:
    handler: lambdaInvokeAsyncHandler.invokeAsync
    events:
      - http:
          method: get
          path: invoke-async

  invokedAsyncHandler:
    handler: lambdaInvokeAsyncHandler.invokedAsyncHandle
