service: so-v6

plugins:
  - serverless-offline

custom:
  serverless-offline:
    # serverless-offline v6
    showDuration: true
    httpPort: 3006
    lambdaPort: 3007

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        #- lambda:InvokeAsync
        - lambda:InvokeFunction
      Resource: '*'
      memorySize: 128
      name: aws
      region: us-east-1
      runtime: nodejs12.x
      stage: dev
      versionFunctions: false

functions:
  invokeEvent:
    events:
      - http:
        method: get
        path: invoke-event
        handler: lambdaInvokeHandler.invokeEvent

  invokeRequestResponse:
    events:
      - http:
        method: get
        path: invoke-request-response
        handler: lambdaInvokeHandler.invokeRequestResponse

  invokedHandler:
    handler: lambdaInvokeHandler.invokedHandler

  invokeAsync:
    events:
      - http:
        method: get
        path: invoke-async
        handler: lambdaInvokeAsyncHandler.invokeAsync

        invokedAsyncHandler:
          handler: lambdaInvokeAsyncHandler.invokedAsyncHandle r
